name: anglemeasurment
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  get: ^4.6.5
  intl: ^0.18.1
  supabase: ^1.11.6
  supabase_flutter: ^1.10.4
  # shared_preferences: ^2.2.1
  # skeletons: ^0.0.3
  rounded_loading_button: ^2.1.0
  # font_awesome_flutter: any
  introduction_screen: any
  cupertino_icons: ^1.0.2
  bottom_navy_bar: ^6.0.0
  animated_text_kit: ^4.2.2
  jumping_dot: ^0.0.6
  video_player: ^2.7.2
  photo_view: ^0.14.0
  image_picker: ^1.0.4
  file_picker: ^5.3.1
  # carousel_slider: ^4.2.1
  flutter_animate: ^4.2.0
  http: ^0.13.6
  animations: ^2.0.7
  url_launcher: any
  dots_indicator: any
  five_pointed_star: ^1.0.3
  flutter_rating_bar: ^4.0.1
  # flutter_chat_ui: ^0.0.2
  open_filex: ^4.3.4
  flutter_chat_types: ^3.6.2
  uuid: ^4.1.0
  # google_maps_flutter: ^2.3.0
  # geocoding: ^2.0.5
  # geolocator: ^9.0.2
  # location: ^4.4.0
  permission_handler: ^10.2.0
  flutter_staggered_animations: ^1.1.1
  animated_button: ^0.2.0
  flutter_animated_button: ^2.0.3
  # date_field: ^3.0.5
  # badges: ^3.1.1
  # flutter_screen_lock: ^9.0.1
  # flutter_otp_text_field: ^1.1.1
  flutter_expandable_fab: ^2.0.0
  # flutter_hooks: ^0.20.3
  # freezed_annotation: ^2.4.1
  # hooks_riverpod: ^2.3.8
  # measure_size: ^4.0.0
  # arkit_plugin: ^1.0.7
  lottie: ^2.3.2
  superdeclarative_geometry: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # build_runner: ^2.3.3
  # freezed: ^2.4.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat.ttf
    #         style: italic
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf
    - family: GreyCliff
      fonts:
        - asset: assets/fonts/greycliff.otf
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
